"""Añadiendo campos a la tabla de productos

Revision ID: 385750f89b02
Revises: 7fb542ebe78b
Create Date: 2023-11-16 22:02:36.415026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385750f89b02'
down_revision: Union[str, None] = '7fb542ebe78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
