"""Añadiendo campos a la tabla de productos

Revision ID: 6191bcd08438
Revises: 2072881b9691
Create Date: 2023-11-16 22:26:28.326371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6191bcd08438'
down_revision: Union[str, None] = '2072881b9691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
