"""Añadiendo campos a la tabla de productos

Revision ID: 764af5813214
Revises: c7d500a40b74
Create Date: 2023-11-16 22:13:25.442274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764af5813214'
down_revision: Union[str, None] = 'c7d500a40b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
