"""Añadiendo campos a la tabla de productos

Revision ID: 7fb542ebe78b
Revises: 61be55430623
Create Date: 2023-11-16 21:58:46.275157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb542ebe78b'
down_revision: Union[str, None] = '61be55430623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
