"""Añadiendo campos a la tabla de productos

Revision ID: e479f962707a
Revises: c9f188cf3045
Create Date: 2023-11-16 22:18:35.520578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e479f962707a'
down_revision: Union[str, None] = 'c9f188cf3045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
